name: Test

on:
  push:
    tags-ignore:
      - 'v**'
  schedule:
    - cron: '0 3 * * 1' # every Monday at 03:00
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies (including dev)
        run: pdm sync --dev

      - name: Lint
        run: pdm run lint

      - name: Run tests
        run: pdm run test
